### ISSUE TITLE
Feedback - Miniex07 - Casper Kaels (LurdKek)

### ISSUE THREAD

**Issue by LurdKek** [Epsilon99/AestheticProgrammingCourse#11]
Hey Mick! 

I love your idea, mainly because I had excactly same idea. This is a funny coincidence i think. Also when I compare my own snakegame with yours, sinse the two iterations of the games using checboxes is very different. (check mine here if you want:  https://lurdkek.github.io/AP2017/miniex07/ and see the differnces for yourself). The snake-game is very pretty, and I can see that you succeded in making the snake only one-pix wide, which i had problems with due to some  threshold settings etc. Overall a fine looking piece, and btw I understand that you had problems with making the code excactly the way you wanted, as I had the same problems.

I would, though, have liked to see the snake in the form of "checked boxes" (like in my own), or som eother use of the boxes being "checked" vs. unchecked. That would have been great! Have you thought about how you could have done this? And now that we have read about objects/classes/constructor functions, how come you didn't make seperate files for the snake etc. But this is minor details, and when I am looking into your code it is beautifully set up and understandable even to the smaller detials. I like your idea, and would definitely be looking forward to hear more about one of the days! Cheers!

**Comment by Epsilon99** [comment]
Thanksnfor your feedback!

In regards to checked and unchecked state, I couldn't find a way to set the state of a created checkbox, and I found it a nusance to recreate buttons, just to change the state. Also it's resource heavy to do so, which drove me away from doing it. 
  In regards to use checkboxes as an interaction, I wanted to, as I briefly mentioned in my readme, to make a teo player game in wich one plays the snake and the other the enviroment (a kind of overlord). This could be placing new fruits or making obstacles, by clicking the checkboxes. Here I would have used the HTML function 'disable' on the checkboxes near the snake, so you couldn't simply instant kill the snake player by placing obstacles in front of the head of the snake.
  Another idea I had, was rhe ability to 'cut' the snake by clicking a checkbox in the snake. This would result in creating multiple snakes you would've had to control. With the benefit of creatig more fruit. High risk/ high reward.

In regards to not creating the snake as its own script, I simply dosen't find it necessary. The only reasons would be to simplyfy the scripts/sketches, but since you said yourself I manged to have a structure that is readable, I don't see the need to make multiple scripts.
  As I see it, I would indeed create it as a standalone script if I needed to refference the snake on more than 1 other script. As I pointet out, you can split it up into multiple scripts for more convinient structure, but I simply didn't have the overview of how I wanted to structure it from the beginning, hence I didn't actually plan to do this project as my hand-in. 
  Had it been in an editor or syntax I knew well, I might have done it out of routine thou. An example would be Unity with C# as language of choice :)
