### ISSUE TITLE
Feedback_Mini_ex6_Martin Skødt

### ISSUE THREAD

**Issue by martinskodt** [Epsilon99/AestheticProgrammingCourse#8]
Hey Mick. Let me first say, im very impressed by your program. Not that it surprises me very much, that you are able to do it. But it is very cool to ses, a project on another technical level, than the rest of the classes. i also like your implementation of game in this exercise, and see why you chose this time to figure out random level generation. That said. It is does not have many emersive qualities. You have made the generation take time and the transformation into "land" is cool to watch. But the end product isn't emersive. 
In your code. in understood most of the for loops though function and variable names. and i like your little notes. But it would be appreciated for the future, if you could give a little explanation for each function. Also it surprised me, that there wasn't a more easy way, to load all the different map skins. 

But in all, a great program, that il think about next time i play Heroes III 😄

**Comment by Epsilon99** [comment]
Hi Martin,

First of, thanks for your feedback, I'm glad you liked it.

I know that the generator is not lending it self too much to the viewer, since, as I stated, game-related generitivity tends to not be too good when it comes to generitivity. I think your use of emersive qualities hits spot on. My initial idea was to show how it evaluates every step in the process, but only have one thread to code with, means that you can't both calculate and draw at the same time. There are work arounds, like the one I did when it draws the graphic. But, it messes up the code, since you can't use for loops. This, I would argue, would have given a bit more emmersive quiality to the program, since it would try and draw the viewer into the 'magic' of the process. But that being said, it would properly still not be too emmersive.

I totally get that there could be more indepth comments, but I strive to try and do what is called 'clean-code', where the code can speak for it self. This is obtained by having proper variable - and function names, which you also stated. However, my old habits of this, is better in small scripts, rather than long 300+ lines of scripts. So I can totally understand what you mean. Furthermore, I had to meet the deadline, so a lot of corners were taken to get to a satisfiable end result.

There is lots of ways to load in the different map skins easier. I'm not used to work with the syntax of eiter Javascript nor P5, so I didn't have the knowhow at hand, when I had to load'em in. So I choose the hack-ish way of just doing it like that.

Heroes III is a excelent game ;)
